In [152]:
import mysql.connector
from bs4 import BeautifulSoup
import requests
import pandas as pd

# Make HTTP get request
url = "https://en.wikipedia.org/wiki/List_of_NFL_franchise_owners"
page = requests.get(url)
page.status_code

# Parse content
content = BeautifulSoup(page.text, "html.parser")
#content.text

# Get data table
table = content.find("table", class_="wikitable sortable")
# Save in Pandas dataframe?
df = pd.read_html(str(table))
df = pd.DataFrame(df[0])
df.describe()
df

,Franchise,Principal Owner(s),Purchase Price,Yearacquired
0,Arizona Cardinals,Estate of Bill Bidwill‡6,"$50,000",1932[1]
1,Atlanta Falcons,Arthur Blank†1,"$545,000,000",2002[2]
2,Baltimore Ravens,Steve Bisciotti†1,$300M & $600M,2000 & 2004[3]
3,Buffalo Bills,Kim and Terry Pegula,"$1,400,000,000",2014[4]
4,Carolina Panthers,David Tepper,"$2,275,000,000",2018[5]
5,Chicago Bears,Virginia Halas McCaskey†‡2,$100,1920[6]
6,Cincinnati Bengals,Mike Brown‡2,>$200M[7],1968[8] & 2011
7,Cleveland Browns,Jimmy and Dee Haslam,"$1,050,000,000[9]",2012[10]
8,Dallas Cowboys,Jerry Jones,"$140,000,000",1989[11]
9,Denver Broncos,"Joe Ellis, trustee6","$71,000,000",1984[12]
10,Detroit Lions,Sheila Ford Hamp†‡[13],"$4,500,000",1963[14][15]
11,Green Bay Packers,"Green Bay Packers, Inc.4",-,1923
12,Houston Texans,Janice McNair and family†‡2,"$700,000,000",1999[16]
13,Indianapolis Colts,Jim Irsay‡,"$19,000,000",1972[17]
14,Jacksonville Jaguars,Shahid Khan,"$760,000,000",2012[18]
15,Kansas City Chiefs,Clark Hunt and siblings‡2,"$25,000",1960[19]
16,Las Vegas Raiders,Carol and Mark Davis (mother and son)†‡,-,2011
17,Los Angeles Chargers,Dean Spanos‡,">$72,000,000",1984[20][21][22]
18,Los Angeles Rams,Stan Kroenke1,$80M & $450M,1995 & 2010[23]
19,Miami Dolphins,Stephen M. Ross†,"$1,000,000,000",2008[24]
20,Minnesota Vikings,Zygi Wilf†,"$600,000,000",2005[25]
21,New England Patriots,Robert Kraft,"$175,000,000",1994[26]
22,New Orleans Saints,Gayle Benson‡,"$64,000,000",1985[27]
23,New York Giants,John Mara‡ (50%)3 Steve Tisch (50%),$500,1925[28]
24,New York Jets,Robert Wood Johnson IV5 and Christopher Wold J...,"$635,000,000",2000[29]
25,Philadelphia Eagles,Jeffrey Lurie,"$185,000,000",1994[30]
26,Pittsburgh Steelers,"Art Rooney II‡1,3 (60%) and family (12%)‡1,2,3","$2,500",1933[31]
27,San Francisco 49ers,Denise DeBartolo York and Jed York‡1,"$17,000,000",1977[32]
28,Seattle Seahawks,"Jody Allen, trustee‡6","$200,000,000",1997[33]
29,Tampa Bay Buccaneers,Bryan Glazer and siblings‡,"$192,000,000",1995[34]
30,Tennessee Titans,Amy Adams Strunk‡ 2,"$25,000",1959[35][36]
31,Washington Football Team,Dan Snyder†,"$800,000,000",1999[37]